@startuml architecture

!include <tupadr3/common>
!include <tupadr3/devicons2/redis>
!include <tupadr3/font-awesome-5/user>
!include <tupadr3/font-awesome-5/server>

FA5_USER(developer, developer)
FA5_SERVER(direct, "HTTP Service")

@enduml
