jobs:
- name: elusivebot-docs
  plan:
  - get: elusivebot-docs-git
    trigger: true
  - task: build-site
    config:
      platform: linux
      inputs:
      - name: elusivebot-docs-git
      outputs:
      - name: elusivebot-docs-site
      # TODO: Would be nice to have prebaked image w/ Python3 & venv
      image_resource:
        name: eclipse-temurin-17-jre
        type: registry-image
        source:
          repository: eclipse-temurin
          tag: 17-jre
      caches:
      - path: $HOME/venv
      - path: /var/cache/apt/archives
      run:
        path: bash
        args:
        - -c
        - |
          set -ex
          apt-get update && apt-get install -y python3 python3-venv graphviz
          python3 -m venv $HOME/venv
          source $HOME/venv/bin/activate
          cd elusivebot-docs-git
          pip3 install -r requirements.txt
          ./bin/build
          cp Dockerfile ../elusivebot-docs-site
          cp -r site ../elusivebot-docs-site/
  - task: build-image
    privileged: true
    config:
      platform: linux
      caches:
      - path: cache
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: elusivebot-docs-site
      outputs:
      - name: image
      params:
        CONTEXT: elusivebot-docs-site
      run:
        path: build
  - put: elusivebot-docs-image
    params:
      image: image/image.tar


resources:
- name: elusivebot-docs-git
  type: git
  icon: github
  source:
    uri: https://github.com/elusivebot/elusivebot-docs.git
    username: ((github.username))
    password: ((github.password))
- name: elusivebot-docs-image
  type: registry-image
  icon: docker
  source:
    repository: ((docker.host))/elusivebot/docs
    username: ((docker.username))
    password: ((docker.password))
    tag: latest

