version: '3.8'
services:
  docs:
    build:
      context: .
    image: "elusivebot/docs:latest"
    container_name: "elusivebot.docs"
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
