services:
  docs:
    build:
      context: .
    image: "docker.degrendel.com/elusivebot/docs:latest"
    container_name: "elusivebot.docs"
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
