@startuml architecture
!include <tupadr3/common>
!include <tupadr3/devicons2/redis>
!include <tupadr3/font-awesome-5/user>
!include <tupadr3/font-awesome-5/server>

FA5_USER(developer, developer)
FA5_SERVER(direct, "Direct Service")

DEV2_REDIS(message_queue, "Message Queue", database)
DEV2_REDIS(response_queue, "Response Queue", database)
DEV2_REDIS(user_state, "User State", database)

developer --> direct : send messages
direct --> developer : receive responses

direct --> user_state : SET user status
direct -> message_queue : RPUSH to main queue
response_queue -> direct : RPUSH to user's queue
@enduml
