@startuml architecture
!include <tupadr3/common>
!include <logos/kafka>
!include <tupadr3/font-awesome-5/user>
!include <tupadr3/font-awesome-5/server>

FA5_USER(developer, developer)
FA5_SERVER(direct, "Direct Service")

queue "<$kafka> Messages" as messages
queue "<$kafka> User Events" as user_events
queue "<$kafka> Responses" as responses

developer --> direct : send messages
direct --> developer : receive responses

direct --> user_events : Set user state
direct -> messages : Push to service specific queue
responses -> direct : Receive generated responses
@enduml
