@startuml architecture

cloud Cloud

node Endpoints {
    [Discord Service] as discord
    [HTTP Service] as http
}

database Redis {
    [Message Log] as message_log
    [User State] as user_state

    [Channel Update] as channel_updates
}

node Messages {
    [Message Processing] as message_processing
}

node Behaviors {
    [Behavior Fanout] as behavior_fanout
    [Pattern Matching] as behavior_patterns
    [TBD Behavior] as behavior_placeholder
}

node Decision {
    [Decider] as decision_service
}

node Executors {
    [Response Service] as response_service
}

Cloud <--> Endpoints

Endpoints --> message_processing
Endpoints --> user_state
Endpoints --> channel_updates

message_processing --> message_log
message_processing --> channel_updates

channel_updates --> behavior_fanout

behavior_fanout --> behavior_patterns
behavior_fanout --> behavior_placeholder

Behaviors ---> Decision

Decision ---> Executors

response_service --> Endpoints

@enduml
