@startuml architecture

cloud Cloud

node Edge {
    [Discord Service] as discord
    [HTTP Service] as http
}

node Data {
    [Message Processing] as message_processing
    [User Processing] as user_processing
}

node Behavior {
    [Pattern Matching] as behavior_patterns
    [TBD Behavior] as behavior_placeholder
}

node Execution {
    [Response Service] as response_service
}

Cloud <--> Edge

Edge ---> Data

Data ---> Behavior

Behavior ---> Execution

Execution --> Data

Execution ---> Edge

@enduml
